In [83]:
import numpy as np


class GameOfLife:
    _neighbors = np.array([(-1,-1),(0,-1),(1,-1),(-1, 0),(1, 0),(-1, 1),(0, 1),(1, 1)])
    
    def __init__(self, width=10, height=10):
        self._width = width
        self._height = height
        self._board = np.random.choice([0, 1], size=(height, width), p=[.7, .3])
        self._board = np.array([
            [0,0,0,0,0],
            [0,0,1,0,0],
            [0,0,1,0,0],
            [0,0,1,0,0],
            [0,0,0,0,0],])
    
    def step(self):
        changes = []
        for y in range(self._height):
            for x in range(self._width):
                pos = (y, x)
                coords = (self._neighbors + pos) % (self._height, self._width)
                t = sum([self._board[tuple(xy)] for xy in coords])
                if 2 > t or t > 3:
                    changes.append([pos, 0])
                elif t == 3:
                    changes.append([pos, 1])
        for pos, val in changes:
            self._board[pos] = val
        return self
    
    def __repr__(self):
        return str(self._board.copy())


gof = GameOfLife(5, 5)
print(gof)
print(gof.step())

[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
